### ISSUE TITLE
Fetch series when metadata fields are missing

### ISSUE THREAD

**Issue by emoszkowski** [micahjsmith/FredData.jl#1]
`get_data` fails without returning the data series when metadata queries fail. For example,
```julia
f = Fred()
data = get_data(f, "PRS85006063"; frequency="q", observation_start="1959-01-01")
```
throws a `KeyError`. Would it be possible to throw a warning but still return the series if non-essential metadata is missing?

**Comment by micahjsmith** [comment]
Thanks. Closed by d8891d957426f857a78c42c2752a61fd63393f0d
