### ISSUE TITLE
Outdated compatibility with DataFrames at General Registry

### ISSUE THREAD

**Issue by FuZhiyu** [micahjsmith/FredData.jl#18]
Hi,

The entry of this package on [general registry](https://github.com/JuliaRegistries/General/blob/1d358e499e38176568e2aad6fcfc45d5c6c48aa8/F/FredData/Compat.toml#L2) is outdated. It doesn't allow for the latest `DataFrames.jl@0.22`.

I'm not familiar with the registry mechanism, but it seems the issue is caused by the compat rule in this form
```
PackageD = ">=0.4, <1"
```
which does not meet the criteria for automatic merging. Could you update the registry info? Many thanks for this handy package!

**Comment by micahjsmith** [comment]
Hi @FuZhiyu I am taking a look at this, thanks for reporting

**Comment by chenwilliam77** [comment]
Hi Micah,

Flagging this problem again. Would it be possible to just release v0.5 with an updated restriction on DataFrames? I've dev'd FredData and had no issue running tests locally with DataFrames at v1.0.0. It'd be super helpful if newer versions of DataFrames could be permitted, as they've reached v1.0 now.

Best,

William

**Comment by micahjsmith** [comment]
@micahjsmith @FuZhiyu For sure, didn't get around to fixing last time but will look this weekend. If you are able, you are welcome to submit a PR that would fix the issue and I can cut a new release

**Comment by micahjsmith** [comment]
Bumped in #19

**Comment by micahjsmith** [comment]
Closed by https://github.com/JuliaRegistries/General/pull/35151
