### ISSUE TITLE
update HTTP

### ISSUE THREAD

**Issue by PaulSoderlind** [micahjsmith/FredData.jl#22]
FredData.jl is currently blocking my attempts to update to the latest http.jl version. Changing Project.toml to

HTTP = "0.8, 0.9, 1.2"

works well on my local machine

**Comment by micahjsmith** [comment]
Hmm, I’ll try to cut a new release today then

--
Micah Smith, PhD

E: ***@***.***
W: www.micahsmith.com/
P: he/him
Z: ET <https://time.is/ET>

**Comment by PaulSoderlind** [comment]
thanks
