### ISSUE TITLE
Make the instructions clearer on how to setup the API

### ISSUE THREAD

**Issue by IljaK91** [micahjsmith/FredData.jl#4]
This may sound like a silly request, but it is not directly obvious to me where I should insert "export FRED_API_KEY=abcdefghijklmnopqrstuvwxyz123456" or the other option.

Could you help me with that also include the explanation in the instructions?

**Comment by micahjsmith** [comment]
Sure thing. Both of those commands can be run directly from your shell on macOS/Linux. If you are on Windows, they would need to be modified somewhat.
